### ISSUE TITLE
Revision-specific gist support

### ISSUE THREAD

**Issue by dhimmel** [neo4j-contrib/graphgist#37]
@jexp [introduced me](https://twitter.com/mesirii/status/677273902247231489) to graphgists and they're awesome.

I made a [graphgist](http://neo4j-contrib.github.io/graphgist/?f69730d8bdfb880c15ed) for my project which I reference in a [comment](http://thinklab.com/d/136#1) on Thinklab—an open science platform we use to chronicle and discuss our research.

We would like however to link to a specific version of the graphgist, since the comment is in the context of specific point in time. Is it possible to specify a revision for a GitHub gist in the GitHub pages [interface](http://neo4j-contrib.github.io/graphgist)?

**Comment by cheerfulstoic** [comment]
Hey @dhimmel !

We've actually got a new GraphGist portal with some better support for different URLs.  Because of this issue I've just added the ability to preview revisions for GitHub gists.  Check it out here:

http://portal.graphgist.org/

If you want to preview a gist you only need to enter the URL and click on "Preview".  There should also be a link that will allow you to open the preview in a new window.

If you'd like to give any feedback about that portal, it's over here:

http://github.com/neo4j-examples/graphgist_portal/issues

The code is also available on GitHub (it's a Rails app), so you could host your own portal if you like.

**Comment by dhimmel** [comment]
Thanks! I was able to preview the revision specific graphgist with [this url](http://portal.graphgist.org/graph_gists/by_url?url=https://gist.github.com/dhimmel/f69730d8bdfb880c15ed/6663d64be53e5b8c438d0a2d55a5778676ccf0b1).

@cheerfulstoic, is http://portal.graphgist.org a longterm solution -- will the portal continue after the competition finishes?

**Comment by cheerfulstoic** [comment]
Yup, the plan is to use the portal after the competition.  There is still some question as to how GraphGists will be displayed so it's not displaying lists of them at the moment, but you can browse them here: http://portal.graphgist.org/graph_gists
